package gopdflib_test

import (
	"bytes"
	"testing"

	"github.com/chinmay-sawant/gopdfsuit/v6/pkg/gopdflib"
)

// tinyPNGBase64 is a 1x1 PNG used for image cells and image elements.
const tinyPNGBase64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="

// TestBuilderReferenceSnippet is the plan's reference snippet verbatim: it
// must compile and generate after Phase 2.
func TestBuilderReferenceSnippet(t *testing.T) {
	b := gopdflib.NewDocument("A4", true)
	b.AddTitle("Document Title", gopdflib.WithTitleFont("Helvetica", 18, true))
	tb := b.AddTable(3, 1, 2, 1)
	row := tb.AddRow(
		gopdflib.NewCell("", "Helvetica:12:000:left:1:1:1:1"),
		gopdflib.NewCell("Document Title", "Helvetica:18:100:center:1:1:1:1"),
		gopdflib.NewCell("", "Helvetica:12:000:right:1:1:1:1"),
	)
	gopdflib.SetCellTextColor(&row[2], "#B00020")
	gopdflib.SetCellFont(&row[1], "Helvetica", 18, true, false, false)
	c := gopdflib.NewCell("clause", gopdflib.MakeProps("Helvetica", 12, false, false, false, "left", [4]int{1, 1, 1, 1}))
	gopdflib.AddBracketText(&c, "[", "]")
	pdfBytes, err := b.Generate()
	if err != nil {
		t.Fatalf("Generate = %v", err)
	}
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF-")) {
		t.Fatal("generated bytes do not start with %PDF-")
	}

	if row[2].TextColor != "#B00020" {
		t.Fatalf("right cell textcolor = %q, want #B00020", row[2].TextColor)
	}
	if row[1].Props != "Helvetica:18:100:center:1:1:1:1" {
		t.Fatalf("middle cell props = %q", row[1].Props)
	}
	if c.Text != "[clause]" {
		t.Fatalf("bracket text = %q, want [clause]", c.Text)
	}
	// The returned row aliases the stored row, so Generate saw the red cell.
	tpl := b.Build()
	if tpl.Table != nil {
		t.Fatal("builder must emit elements, not the legacy table field")
	}
	if len(tpl.Elements) != 1 || tpl.Elements[0].Table == nil {
		t.Fatalf("elements = %+v, want one table", tpl.Elements)
	}
	stored := tpl.Elements[0].Table.Rows[0].Row
	if stored[2].TextColor != "#B00020" {
		t.Fatalf("stored right cell textcolor = %q, want #B00020", stored[2].TextColor)
	}
}

func TestBuilderTitleTableSpacerImage(t *testing.T) {
	b := gopdflib.NewDocument("A4", true)
	b.AddTitle("Report", gopdflib.WithTitleFont("Helvetica", 18, true))

	ttb := b.AddTitleTable(3, 1, 2, 1)
	ttb.AddRow(
		gopdflib.HeaderCell("Left"),
		gopdflib.HeaderCell("Title"),
		gopdflib.HeaderCell("Right"),
	)

	b.AddSpacer(20)
	b.AddImage("dot.png", tinyPNGBase64, 100, 80)

	tb := b.AddTable(2, 1, 1)
	tb.AddRow(
		gopdflib.NewCell("plain", gopdflib.MakeProps("Helvetica", 10, false, false, false, "left", [4]int{1, 1, 1, 1})),
		gopdflib.NewImageCell("dot.png", tinyPNGBase64, 100, 80,
			gopdflib.MakeProps("Helvetica", 10, false, false, false, "center", [4]int{1, 1, 1, 1})),
	)

	tpl := b.Build()
	if tpl.Title.Table == nil || tpl.Title.Table.MaxColumns != 3 {
		t.Fatalf("title table = %+v, want 3 columns", tpl.Title.Table)
	}
	if len(tpl.Title.Table.Rows) != 1 || len(tpl.Title.Table.Rows[0].Row) != 3 {
		t.Fatalf("title table rows = %+v, want one 3-cell row", tpl.Title.Table.Rows)
	}
	if len(tpl.Elements) != 3 {
		t.Fatalf("elements = %d, want spacer + image + table", len(tpl.Elements))
	}
	if tpl.Elements[0].Spacer == nil || tpl.Elements[0].Spacer.Height != 20 {
		t.Fatalf("spacer = %+v, want height 20", tpl.Elements[0].Spacer)
	}
	img := tpl.Elements[1].Image
	if img == nil || img.Width != 100 || img.Height != 80 {
		t.Fatalf("image = %+v, want 100x80", img)
	}

	pdfBytes, err := b.Generate()
	if err != nil {
		t.Fatalf("Generate = %v", err)
	}
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF-")) {
		t.Fatal("generated bytes do not start with %PDF-")
	}
}

func TestBuilderCellColors(t *testing.T) {
	b := gopdflib.NewDocument("Letter", false)
	if tpl := b.Build(); tpl.Config.PageAlignment != 2 {
		t.Fatalf("landscape alignment = %d, want 2", tpl.Config.PageAlignment)
	}

	tb := b.AddTable(2, 1, 1)
	row := tb.AddRow(
		gopdflib.NewCell("a", gopdflib.MakeProps("Helvetica", 12, false, false, false, "left", [4]int{1, 1, 1, 1})),
		gopdflib.NewCell("b", gopdflib.MakeProps("Helvetica", 12, false, false, false, "right", [4]int{1, 1, 1, 1})),
	)
	// Different color on the right cell.
	gopdflib.SetCellTextColor(&row[1], "#B00020")
	gopdflib.SetCellBgColor(&row[0], "#F5F5F5")
	if row[1].TextColor != "#B00020" || row[0].BgColor != "#F5F5F5" {
		t.Fatalf("per-cell colors = %+v", row)
	}

	gopdflib.SetRowColor(row, "#EEEEEE", "#111111")
	for i, cell := range row {
		if cell.BgColor != "#EEEEEE" || cell.TextColor != "#111111" {
			t.Fatalf("row color cell %d = %+v", i, cell)
		}
	}

	gopdflib.SetTableColors(tb, "#FFFFFF", "#000000")
	stored := b.Build().Elements[0].Table.Rows[0].Row
	for i, cell := range stored {
		if cell.BgColor != "#FFFFFF" || cell.TextColor != "#000000" {
			t.Fatalf("table color cell %d = %+v", i, cell)
		}
	}

	gopdflib.SetCellColor(&stored[0], "#AABBCC", "#112233")
	if stored[0].BgColor != "#AABBCC" || stored[0].TextColor != "#112233" {
		t.Fatalf("SetCellColor = %+v", stored[0])
	}
}

func TestBuilderCellFontHelpers(t *testing.T) {
	c := gopdflib.NewCell("x", "Helvetica:12:000:left:1:0:1:0")
	gopdflib.SetCellFont(&c, "Courier", 14, true, true, false)
	if c.Props != "Courier:14:110:left:1:0:1:0" {
		t.Fatalf("SetCellFont = %q, want alignment/borders preserved", c.Props)
	}
	gopdflib.SetCellAlignment(&c, "right")
	gopdflib.SetCellBorders(&c, [4]int{0, 0, 0, 0})
	if c.Props != "Courier:14:110:right:0:0:0:0" {
		t.Fatalf("align/borders = %q", c.Props)
	}

	h := gopdflib.HeaderCell("H")
	if h.Props != "Helvetica:12:100:center:1:1:1:1" {
		t.Fatalf("HeaderCell props = %q", h.Props)
	}
	m := gopdflib.MathCell("y = x^2")
	if m.MathEnabled == nil || !*m.MathEnabled {
		t.Fatalf("MathCell mathEnabled = %+v, want true", m.MathEnabled)
	}

	gopdflib.SetBracketFont(&c, "Times-Roman", 16)
	if c.Props != "Times-Roman:16:110:right:0:0:0:0" {
		t.Fatalf("SetBracketFont = %q", c.Props)
	}

	// Nil receivers are no-ops, not panics.
	gopdflib.SetCellFont(nil, "Helvetica", 12, false, false, false)
	gopdflib.SetCellAlignment(nil, "center")
	gopdflib.SetCellBorders(nil, [4]int{1, 1, 1, 1})
	gopdflib.SetCellColor(nil, "#FFF", "#000")
	gopdflib.SetCellTextColor(nil, "#000")
	gopdflib.SetCellBgColor(nil, "#FFF")
	gopdflib.SetRowColor(nil, "#FFF", "#000")
	gopdflib.SetTableColors(nil, "#FFF", "#000")
	gopdflib.AddBracketText(nil, "[", "]")
	gopdflib.SetBracketFont(nil, "Helvetica", 12)
	var nilBuilder *gopdflib.DocumentBuilder
	nilBuilder.AddTitle("nope")
	nilBuilder.AddSpacer(5)
	nilBuilder.AddImage("x", "", 1, 1)
	if tpl := nilBuilder.Build(); len(tpl.Elements) != 0 {
		t.Fatalf("nil builder Build elements = %d", len(tpl.Elements))
	}
	if _, err := nilBuilder.Generate(); err == nil {
		t.Fatal("nil builder Generate must fail")
	}
}
