package pdf

import (
	"testing"

	"github.com/chinmay-sawant/gopdfsuit/v6/internal/models"
)

// BenchmarkBOPS is the standard Go benchmark for bypass-cache PDF
// generation. Each iteration clears content caches and renders a unique
// template so b.N measures cold-path cost, not warm cache hits.
//
// Run: go test -run='^$' -bench='BenchmarkBOPS' -benchmem -count=1 ./internal/pdf
func BenchmarkBOPS(b *testing.B) {
	records := loadBenchmarkData()
	b.ResetTimer()
	for i := 0; b.Loop(); i++ {
		ClearPropsCache()
		ResetImageCache()
		template := getGoPdfSuitTemplate(records)
		// Unique marker defeats content dedup across iterations.
		template.Config.PdfTitle = "BOPS Report"
		if len(template.Table) > 0 && len(template.Table[0].Rows) > 0 {
			template.Table[0].Rows[0].Row[0].Text = "BOPS row marker"
		}
		_ = i
		pdfBytes, err := GenerateTemplatePDF(template)
		if err != nil {
			b.Fatalf("Failed to generate PDF: %v", err)
		}
		if len(pdfBytes) == 0 {
			b.Fatalf("Generated empty PDF")
		}
		b.ReportMetric(float64(len(pdfBytes)), "bytes/op")
	}
}

// BenchmarkBOPSRetail is the Zerodha-shaped variant: fresh small template
// per op with props and image caches cleared, mirroring the BOPS runner.
func BenchmarkBOPSRetail(b *testing.B) {
	b.ResetTimer()
	for i := 0; b.Loop(); i++ {
		ClearPropsCache()
		ResetImageCache()
		template := models.PDFTemplate{
			Config: pdfAConfig(),
			Title: models.Title{
				Text:  "BOPS Contract Note",
				Props: "Helvetica:24:100:center:0:0:0:0",
			},
			Footer: models.Footer{
				Font: "Helvetica:10:000:center",
				Text: "Generated by gopdfsuit BOPS",
			},
		}
		template.Table = []models.Table{{
			MaxColumns:   2,
			ColumnWidths: []float64{1, 2},
			Rows: []models.Row{{Row: []models.Cell{
				{Props: "Helvetica:10:000:left:1:1:1:1", Text: "BOPS marker"},
				{Props: "Helvetica:10:000:left:1:1:1:1", Text: "iteration payload"},
			}}},
		}}
		pdfBytes, err := GenerateTemplatePDF(template)
		if err != nil {
			b.Fatalf("Failed to generate PDF: %v", err)
		}
		if len(pdfBytes) == 0 {
			b.Fatalf("Generated empty PDF")
		}
		b.ReportMetric(float64(len(pdfBytes)), "bytes/op")
	}
}
