runtime: go124  # Or your specific runtime (python310, nodejs20, etc.)
instance_class: F1

automatic_scaling:
  max_instances: 1       # STRICT LIMIT: Never spin up a 2nd instance
  min_instances: 1       # OPTIONAL: Keeps 1 instance alive 24x7 (prevents cold starts)
  max_concurrent_requests: 80 # Tuning for single instance throughput

main: ./cmd/gopdfsuit 

# Optional: Environment variables
env_variables:
  # Google OAuth Client ID
  # Get this from Google Cloud Console: https://console.cloud.google.com/apis/credentials
  VITE_GOOGLE_CLIENT_ID: "19813699538-fg04b6hm2s0tttjjkk7dkhhbi9acn7pk.apps.googleusercontent.com"
  GOOGLE_CLIENT_ID: "19813699538-fg04b6hm2s0tttjjkk7dkhhbi9acn7pk.apps.googleusercontent.com"

  # For Cloud Run deployment
  VITE_IS_CLOUD_RUN: "true"
  VITE_ENVIRONMENT: "cloudrun"
  VITE_CLOUD_RUN_URL: "https://gopdfsuit.ue.r.appspot.com"
  VITE_API_URL: "https://gopdfsuit.ue.r.appspot.com"
  CLOUD_RUN_SERVICE_URL: "https://gopdfsuit.ue.r.appspot.com"