// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chinmay-sawant/gopdfsuit/v6/internal/handlers (interfaces: PDFService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_services.go -package=mocks github.com/chinmay-sawant/gopdfsuit/v6/internal/handlers PDFService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/chinmay-sawant/gopdfsuit/v6/internal/models"
	merge "github.com/chinmay-sawant/gopdfsuit/v6/internal/pdf/merge"
	gomock "go.uber.org/mock/gomock"
)

// MockPDFService is a mock of PDFService interface.
type MockPDFService struct {
	ctrl     *gomock.Controller
	recorder *MockPDFServiceMockRecorder
	isgomock struct{}
}

// MockPDFServiceMockRecorder is the mock recorder for MockPDFService.
type MockPDFServiceMockRecorder struct {
	mock *MockPDFService
}

// NewMockPDFService creates a new mock instance.
func NewMockPDFService(ctrl *gomock.Controller) *MockPDFService {
	mock := &MockPDFService{ctrl: ctrl}
	mock.recorder = &MockPDFServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPDFService) EXPECT() *MockPDFServiceMockRecorder {
	return m.recorder
}

// FillPDFWithXFDF mocks base method.
func (m *MockPDFService) FillPDFWithXFDF(pdfBytes, xfdfBytes []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FillPDFWithXFDF", pdfBytes, xfdfBytes)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FillPDFWithXFDF indicates an expected call of FillPDFWithXFDF.
func (mr *MockPDFServiceMockRecorder) FillPDFWithXFDF(pdfBytes, xfdfBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FillPDFWithXFDF", reflect.TypeOf((*MockPDFService)(nil).FillPDFWithXFDF), pdfBytes, xfdfBytes)
}

// GenerateTemplatePDF mocks base method.
func (m *MockPDFService) GenerateTemplatePDF(template models.PDFTemplate) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTemplatePDF", template)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTemplatePDF indicates an expected call of GenerateTemplatePDF.
func (mr *MockPDFServiceMockRecorder) GenerateTemplatePDF(template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTemplatePDF", reflect.TypeOf((*MockPDFService)(nil).GenerateTemplatePDF), template)
}

// MergePDFs mocks base method.
func (m *MockPDFService) MergePDFs(pdfBytesList [][]byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePDFs", pdfBytesList)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePDFs indicates an expected call of MergePDFs.
func (mr *MockPDFServiceMockRecorder) MergePDFs(pdfBytesList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePDFs", reflect.TypeOf((*MockPDFService)(nil).MergePDFs), pdfBytesList)
}

// SplitPDF mocks base method.
func (m *MockPDFService) SplitPDF(pdfBytes []byte, spec merge.SplitSpec) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitPDF", pdfBytes, spec)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitPDF indicates an expected call of SplitPDF.
func (mr *MockPDFServiceMockRecorder) SplitPDF(pdfBytes, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitPDF", reflect.TypeOf((*MockPDFService)(nil).SplitPDF), pdfBytes, spec)
}
