// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chinmay-sawant/gopdfsuit/v6/internal/handlers (interfaces: PDFService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_services.go -package=mocks github.com/chinmay-sawant/gopdfsuit/v6/internal/handlers PDFService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/chinmay-sawant/gopdfsuit/v6/internal/models"
	compress "github.com/chinmay-sawant/gopdfsuit/v6/internal/pdf/compress"
	merge "github.com/chinmay-sawant/gopdfsuit/v6/internal/pdf/merge"
	gomock "go.uber.org/mock/gomock"
)

// MockPDFService is a mock of PDFService interface.
type MockPDFService struct {
	ctrl     *gomock.Controller
	recorder *MockPDFServiceMockRecorder
	isgomock struct{}
}

// MockPDFServiceMockRecorder is the mock recorder for MockPDFService.
type MockPDFServiceMockRecorder struct {
	mock *MockPDFService
}

// NewMockPDFService creates a new mock instance.
func NewMockPDFService(ctrl *gomock.Controller) *MockPDFService {
	mock := &MockPDFService{ctrl: ctrl}
	mock.recorder = &MockPDFServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPDFService) EXPECT() *MockPDFServiceMockRecorder {
	return m.recorder
}

// CompressPDF mocks base method.
func (m *MockPDFService) CompressPDF(pdfBytes []byte, opts compress.Options) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompressPDF", pdfBytes, opts)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompressPDF indicates an expected call of CompressPDF.
func (mr *MockPDFServiceMockRecorder) CompressPDF(pdfBytes, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompressPDF", reflect.TypeOf((*MockPDFService)(nil).CompressPDF), pdfBytes, opts)
}

// FillPDFWithXFDF mocks base method.
func (m *MockPDFService) FillPDFWithXFDF(pdfBytes, xfdfBytes []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FillPDFWithXFDF", pdfBytes, xfdfBytes)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FillPDFWithXFDF indicates an expected call of FillPDFWithXFDF.
func (mr *MockPDFServiceMockRecorder) FillPDFWithXFDF(pdfBytes, xfdfBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FillPDFWithXFDF", reflect.TypeOf((*MockPDFService)(nil).FillPDFWithXFDF), pdfBytes, xfdfBytes)
}

// GenerateTemplatePDF mocks base method.
func (m *MockPDFService) GenerateTemplatePDF(template models.PDFTemplate) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTemplatePDF", template)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTemplatePDF indicates an expected call of GenerateTemplatePDF.
func (mr *MockPDFServiceMockRecorder) GenerateTemplatePDF(template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTemplatePDF", reflect.TypeOf((*MockPDFService)(nil).GenerateTemplatePDF), template)
}

// GetFonts mocks base method.
func (m *MockPDFService) GetFonts() []models.FontInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFonts")
	ret0, _ := ret[0].([]models.FontInfo)
	return ret0
}

// GetFonts indicates an expected call of GetFonts.
func (mr *MockPDFServiceMockRecorder) GetFonts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFonts", reflect.TypeOf((*MockPDFService)(nil).GetFonts))
}

// HTMLToImage mocks base method.
func (m *MockPDFService) HTMLToImage(req models.HTMLToImageRequest) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTMLToImage", req)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HTMLToImage indicates an expected call of HTMLToImage.
func (mr *MockPDFServiceMockRecorder) HTMLToImage(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTMLToImage", reflect.TypeOf((*MockPDFService)(nil).HTMLToImage), req)
}

// HTMLToPDF mocks base method.
func (m *MockPDFService) HTMLToPDF(req models.HTMLToPDFRequest) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTMLToPDF", req)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HTMLToPDF indicates an expected call of HTMLToPDF.
func (mr *MockPDFServiceMockRecorder) HTMLToPDF(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTMLToPDF", reflect.TypeOf((*MockPDFService)(nil).HTMLToPDF), req)
}

// MergePDFs mocks base method.
func (m *MockPDFService) MergePDFs(pdfBytesList [][]byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePDFs", pdfBytesList)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePDFs indicates an expected call of MergePDFs.
func (mr *MockPDFServiceMockRecorder) MergePDFs(pdfBytesList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePDFs", reflect.TypeOf((*MockPDFService)(nil).MergePDFs), pdfBytesList)
}

// RegisterFont mocks base method.
func (m *MockPDFService) RegisterFont(name string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterFont", name, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterFont indicates an expected call of RegisterFont.
func (mr *MockPDFServiceMockRecorder) RegisterFont(name, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterFont", reflect.TypeOf((*MockPDFService)(nil).RegisterFont), name, data)
}

// SplitPDF mocks base method.
func (m *MockPDFService) SplitPDF(pdfBytes []byte, spec merge.SplitSpec) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitPDF", pdfBytes, spec)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitPDF indicates an expected call of SplitPDF.
func (mr *MockPDFServiceMockRecorder) SplitPDF(pdfBytes, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitPDF", reflect.TypeOf((*MockPDFService)(nil).SplitPDF), pdfBytes, spec)
}
