package redact

import "regexp"

// Package-level compiled regexes (PERF-1: avoid MustCompile inside loops).
var (
	reTrailerDict       = regexp.MustCompile(`trailer(?s).*?<<(.*?)>>`)
	reRootRef           = regexp.MustCompile(`/Root\s+(\d+)\s+(\d+)\s+R`)
	reObjStream         = regexp.MustCompile(`(?s)(\d+)\s+(\d+)\s+obj(.*?)endobj`)
	reStreamSegment     = regexp.MustCompile(`(?s)stream\s*\r?\n(.*?)\r?\nendstream`)
	reObjAtOffset       = regexp.MustCompile(`(?s)^(\s*)(\d+)\s+(\d+)\s+obj(.*?)endobj`)
	rePDFObj            = regexp.MustCompile(`(?s)(\d+)\s+(\d+)\s+obj(.*?)endobj`)
	reEncryptRef        = regexp.MustCompile(`/Encrypt\s+(\d+)\s+(\d+)\s+R`)
	reTrailerBlock      = regexp.MustCompile(`(?s)trailer\s*<<(.*?)>>`)
	reTrailerIDHex      = regexp.MustCompile(`/ID\s*\[\s*<([0-9A-Fa-f\s]+)>`)
	reDecryptStream     = regexp.MustCompile(`(?s)stream\s*\r?\n(.*?)\r?\nendstream`)
	reLengthReplace     = regexp.MustCompile(`/Length\s+\d+`)
	reLengthIndirect    = regexp.MustCompile(`/Length\s+\d+\s+\d+\s+R`)
	reLengthInline      = regexp.MustCompile(`/Length\s+(\d+)`)
	reLengthStream      = regexp.MustCompile(`/Length\s+(?:\d+\s+\d+\s+R|\d+)`)
	rePagesRef          = regexp.MustCompile(`/Pages\s+(\d+)\s+(\d+)\s+R`)
	reContents          = regexp.MustCompile(`/Contents\s+(?:(\d+)\s+(\d+)\s+R|\[(.*?)\])`)
	reContentsAlt       = regexp.MustCompile(`/Contents\s+(?:(\d+\s+\d+\s+R)|\[(.*?)\])`)
	reObjRef            = regexp.MustCompile(`(\d+)\s+(\d+)\s+R`)
	reMediaBox          = regexp.MustCompile(`/MediaBox\s*\[\s*([\d.-]+)\s+([\d.-]+)\s+([\d.-]+)\s+([\d.-]+)\s*\]`)
	reMediaBoxRef       = regexp.MustCompile(`/MediaBox\s+(\d+)\s+(\d+)\s+R`)
	reFloatArray        = regexp.MustCompile(`\[\s*([\d.-]+)\s+([\d.-]+)\s+([\d.-]+)\s+([\d.-]+)\s*\]`)
	reFirstField        = regexp.MustCompile(`/First\s+(\d+)`)
	reParentRef         = regexp.MustCompile(`/Parent\s+(\d+)\s+(\d+)\s+R`)
	reInlineResources   = regexp.MustCompile(`(?s)/Resources\s*<<(.*?)>>`)
	reResourcesRef      = regexp.MustCompile(`/Resources\s+(\d+)\s+(\d+)\s+R`)
	reResourceDict      = regexp.MustCompile(`(?s)<<(.*?)>>`)
	reDoOperator        = regexp.MustCompile(`/([A-Za-z0-9_.+-]+)\s+Do`)
	reXObjectDict       = regexp.MustCompile(`(?s)/XObject\s*<<(.*?)>>`)
	reXObjectRef        = regexp.MustCompile(`/([A-Za-z0-9_.+-]+)\s+(\d+)\s+(\d+)\s+R`)
	reFormSubtype       = regexp.MustCompile(`/Subtype\s*/Form(\b|\s|/)`)
	reTypePage          = regexp.MustCompile(`/Type\s*/Page(\b|\s|/)`)
	reTypePages         = regexp.MustCompile(`/Type\s*/Pages(\b|\s|/)`)
	reKidsArray         = regexp.MustCompile(`/Kids\s*\[(.*?)\]`)
	reKidsSingle        = regexp.MustCompile(`/Kids\s+(\d+)\s+(\d+)\s+R`)
	reBTET              = regexp.MustCompile(`(?s)BT(.*?)ET`)
	reTm                = regexp.MustCompile(`([\d.-]+)\s+([\d.-]+)\s+([\d.-]+)\s+([\d.-]+)\s+([\d.-]+)\s+([\d.-]+)\s+Tm`)
	reTd                = regexp.MustCompile(`([\d.-]+)\s+([\d.-]+)\s+T[dD]`)
	reTf                = regexp.MustCompile(`/[A-Za-z0-9_.+-]+\s+([\d.-]+)\s+Tf`)
	reTextOp            = regexp.MustCompile(`(?s)\[(?:.|\n|\r)*?\]\s*TJ|<[^>]+>\s*Tj|\((?:\\.|[^\\)])*\)\s*Tj|\((?:\\.|[^\\)])*\)\s*'|[\d.-]+\s+[\d.-]+\s+\((?:\\.|[^\\)])*\)\s*"`)
	reToken             = regexp.MustCompile(`(?s)[\d.-]+\s+[\d.-]+\s+[\d.-]+\s+[\d.-]+\s+[\d.-]+\s+[\d.-]+\s+Tm|[\d.-]+\s+[\d.-]+\s+T[dD]|/[A-Za-z0-9_.+-]+\s+([\d.-]+)\s+Tf|\[(?:.|\n|\r)*?\]\s*TJ|<[^>]+>\s*Tj|\((?:\\.|[^\\)])*\)\s*Tj|\((?:\\.|[^\\)])*\)\s*'|[\d.-]+\s+[\d.-]+\s+\((?:\\.|[^\\)])*\)\s*"`)
	reTrailerRebuild    = regexp.MustCompile(`(?s)trailer\s*<<(.*?)>>`)
	reTrailerID         = regexp.MustCompile(`(?s)/ID\s*(\[(?:.|\n|\r)*?\])`)
	reStartXRefEOF      = regexp.MustCompile(`(?s)startxref\s*(\d+)\s*%%EOF\s*$`)
	reStartXRefAny      = regexp.MustCompile(`startxref\s*(\d+)`)
)

// Common byte literals to avoid repeated []byte("...") conversions in hot paths.
var (
	encryptSubBytes     = []byte("/Encrypt")
	encryptFilterStd    = []byte(`/Filter /Standard`)
	encryptFilterStdAlt = []byte(`/Filter/Standard`)
	encryptMetaFalse    = []byte(`/EncryptMetadata false`)
	encryptMetaFalseAlt = []byte(`/EncryptMetadatafalse`)
	aesV2Bytes          = []byte("/AESV2")
	aesV3Bytes          = []byte("/AESV3")
	flateDecodeBytes    = []byte("/FlateDecode")
	imageBytes          = []byte("/Image")
	objStmBytes         = []byte("/ObjStm")
	objStmTypeBytes     = []byte("/Type/ObjStm")
	wFieldBytes         = []byte(`/W[`)
	indexFieldBytes     = []byte(`/Index`)
)